var FlatmapsDialog = require("./flatmapsDialog").FlatmapsDialog;
var FlatmapsModule = require("./flatmapsDialog").FlatmapsModule;
var PlotsvyDialog = require("./plotsvyDialog").PlotsvyDialog;
var PlotsvyModule = require("./plotsvyDialog").PlotsvyModule;
let SimulationDialog = require("./simulation").SimulationDialog;
let SimulationModule = require("./simulation").SimulationModule;
let BiolucidaDialog = require("./biolucida").BiolucidaDialog;
let BiolucidaModule = require("./biolucida").BiolucidaModule;
exports.FlatmapsDialog = FlatmapsDialog;
exports.FlatmapsModule = FlatmapsModule;
exports.PlotsvyDialog = PlotsvyDialog;
exports.PlotsvyModule = PlotsvyModule;
exports.SimulationDialog = SimulationDialog;
exports.SimulationModule = SimulationModule;
exports.BiolucidaDialog = BiolucidaDialog;
exports.BiolucidaModule = BiolucidaModule;
exports.physiomeportal = require("physiomeportal");
require('physiomeportal/src/styles/dat-gui-swec.css');
