let FlatmapsDialog = require("./flatmapsDialog").FlatmapsDialog;
let FlatmapsModule = require("./flatmapsDialog").FlatmapsModule;
let BFCSVExporterDialog = require("./BFCSVExporterDialog").BFCSVExporterDialog;
let BFCSVExporterModule = require("./BFCSVExporterDialog").BFCSVExporterModule;
let SimulationDialog = require("./simulation").SimulationDialog;
let SimulationModule = require("./simulation").SimulationModule;
exports.FlatmapsDialog = FlatmapsDialog;
exports.FlatmapsModule = FlatmapsModule;
exports.BFCSVExporterDialog = BFCSVExporterDialog;
exports.BFCSVExporterModule = BFCSVExporterModule;
exports.SimulationDialog = SimulationDialog;
exports.SimulationModule = SimulationModule;
exports.physiomeportal = require("physiomeportal");
require('physiomeportal/src/styles/dat-gui-swec.css');
